import paddle
import math
from x2paddle.op_mapper.onnx2paddle import onnx_custom_layer as x2paddle_nn

class ONNXModel(paddle.nn.Layer):
    def __init__(self):
        super(ONNXModel, self).__init__()
        self.conv0 = paddle.nn.Conv2D(in_channels=3, out_channels=24, kernel_size=[3, 3], stride=2, padding=1)
        self.relu0 = paddle.nn.ReLU()
        self.pool0 = paddle.nn.MaxPool2D(kernel_size=[3, 3], stride=2, padding=1)
        self.conv1 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[3, 3], stride=2, padding=1, groups=24)
        self.conv2 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[1, 1])
        self.conv3 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[1, 1])
        self.relu1 = paddle.nn.ReLU()
        self.relu2 = paddle.nn.ReLU()
        self.conv4 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[3, 3], stride=2, padding=1, groups=24)
        self.conv5 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[1, 1])
        self.relu3 = paddle.nn.ReLU()
        self.conv6 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[1, 1])
        self.relu4 = paddle.nn.ReLU()
        self.conv7 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[3, 3], padding=1, groups=24)
        self.conv8 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[1, 1])
        self.relu5 = paddle.nn.ReLU()
        self.conv9 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[1, 1])
        self.relu6 = paddle.nn.ReLU()
        self.conv10 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[3, 3], padding=1, groups=24)
        self.conv11 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[1, 1])
        self.relu7 = paddle.nn.ReLU()
        self.conv12 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[1, 1])
        self.relu8 = paddle.nn.ReLU()
        self.conv13 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[3, 3], padding=1, groups=24)
        self.conv14 = paddle.nn.Conv2D(in_channels=24, out_channels=24, kernel_size=[1, 1])
        self.relu9 = paddle.nn.ReLU()
        self.conv15 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[3, 3], stride=2, padding=1, groups=48)
        self.conv16 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.conv17 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu10 = paddle.nn.ReLU()
        self.relu11 = paddle.nn.ReLU()
        self.conv18 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[3, 3], stride=2, padding=1, groups=48)
        self.conv19 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu12 = paddle.nn.ReLU()
        self.conv20 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu13 = paddle.nn.ReLU()
        self.conv21 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[3, 3], padding=1, groups=48)
        self.conv22 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu14 = paddle.nn.ReLU()
        self.conv23 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu15 = paddle.nn.ReLU()
        self.conv24 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[3, 3], padding=1, groups=48)
        self.conv25 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu16 = paddle.nn.ReLU()
        self.conv26 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu17 = paddle.nn.ReLU()
        self.conv27 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[3, 3], padding=1, groups=48)
        self.conv28 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu18 = paddle.nn.ReLU()
        self.conv29 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu19 = paddle.nn.ReLU()
        self.conv30 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[3, 3], padding=1, groups=48)
        self.conv31 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu20 = paddle.nn.ReLU()
        self.conv32 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu21 = paddle.nn.ReLU()
        self.conv33 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[3, 3], padding=1, groups=48)
        self.conv34 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu22 = paddle.nn.ReLU()
        self.conv35 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu23 = paddle.nn.ReLU()
        self.conv36 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[3, 3], padding=1, groups=48)
        self.conv37 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu24 = paddle.nn.ReLU()
        self.conv38 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu25 = paddle.nn.ReLU()
        self.conv39 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[3, 3], padding=1, groups=48)
        self.conv40 = paddle.nn.Conv2D(in_channels=48, out_channels=48, kernel_size=[1, 1])
        self.relu26 = paddle.nn.ReLU()
        self.conv41 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[3, 3], stride=2, padding=1, groups=96)
        self.conv42 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[1, 1])
        self.conv43 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[1, 1])
        self.relu27 = paddle.nn.ReLU()
        self.relu28 = paddle.nn.ReLU()
        self.conv44 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[3, 3], stride=2, padding=1, groups=96)
        self.conv45 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[1, 1])
        self.relu29 = paddle.nn.ReLU()
        self.conv46 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[1, 1])
        self.relu30 = paddle.nn.ReLU()
        self.conv47 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[3, 3], padding=1, groups=96)
        self.conv48 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[1, 1])
        self.relu31 = paddle.nn.ReLU()
        self.conv49 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[1, 1])
        self.relu32 = paddle.nn.ReLU()
        self.conv50 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[3, 3], padding=1, groups=96)
        self.conv51 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[1, 1])
        self.relu33 = paddle.nn.ReLU()
        self.conv52 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[1, 1])
        self.relu34 = paddle.nn.ReLU()
        self.conv53 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[3, 3], padding=1, groups=96)
        self.conv54 = paddle.nn.Conv2D(in_channels=96, out_channels=96, kernel_size=[1, 1])
        self.relu35 = paddle.nn.ReLU()

    def forward(self, x2paddle_input_1):
        x2paddle__first_conv_first_conv_0_Constant_output_0 = paddle.full(dtype='int64', shape=[1], fill_value=1)
        x2paddle__stage2_stage2_1_Constant_2_output_0 = paddle.full(dtype='int64', shape=[1], fill_value=0)
        x2paddle__first_conv_first_conv_0_Conv_output_0 = self.conv0(x2paddle_input_1)
        x2paddle__first_conv_first_conv_2_Relu_output_0 = self.relu0(x2paddle__first_conv_first_conv_0_Conv_output_0)
        x2paddle__maxpool_MaxPool_output_0 = self.pool0(x2paddle__first_conv_first_conv_2_Relu_output_0)
        x2paddle__stage2_stage2_0_branch_proj_branch_proj_0_Conv_output_0 = self.conv1(x2paddle__maxpool_MaxPool_output_0)
        x2paddle__stage2_stage2_0_branch_main_branch_main_0_Conv_output_0 = self.conv2(x2paddle__maxpool_MaxPool_output_0)
        x2paddle__stage2_stage2_0_branch_proj_branch_proj_2_Conv_output_0 = self.conv3(x2paddle__stage2_stage2_0_branch_proj_branch_proj_0_Conv_output_0)
        x2paddle__stage2_stage2_0_branch_main_branch_main_2_Relu_output_0 = self.relu1(x2paddle__stage2_stage2_0_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage2_stage2_0_branch_proj_branch_proj_4_Relu_output_0 = self.relu2(x2paddle__stage2_stage2_0_branch_proj_branch_proj_2_Conv_output_0)
        x2paddle__stage2_stage2_0_branch_main_branch_main_3_Conv_output_0 = self.conv4(x2paddle__stage2_stage2_0_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage2_stage2_0_branch_main_branch_main_5_Conv_output_0 = self.conv5(x2paddle__stage2_stage2_0_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage2_stage2_0_branch_main_branch_main_7_Relu_output_0 = self.relu3(x2paddle__stage2_stage2_0_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage2_stage2_0_Concat_output_0 = paddle.concat(x=[x2paddle__stage2_stage2_0_branch_proj_branch_proj_4_Relu_output_0, x2paddle__stage2_stage2_0_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage2_stage2_1_Reshape_output_0 = paddle.reshape(x=x2paddle__stage2_stage2_0_Concat_output_0, shape=[24, 2, 784])
        x2paddle__stage2_stage2_1_Transpose_output_0 = paddle.transpose(x=x2paddle__stage2_stage2_1_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage2_stage2_1_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage2_stage2_1_Transpose_output_0, shape=[2, -1, 24, 28, 28])
        x2paddle__stage2_stage2_1_Gather_output_0 = paddle.gather(x=x2paddle__stage2_stage2_1_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage2_stage2_1_Gather_output_0 = paddle.squeeze(x=x2paddle__stage2_stage2_1_Gather_output_0, axis=[0])
        x2paddle__stage2_stage2_1_Gather_1_output_0 = paddle.gather(x=x2paddle__stage2_stage2_1_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage2_stage2_1_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage2_stage2_1_Gather_1_output_0, axis=[0])
        x2paddle__stage2_stage2_1_branch_main_branch_main_0_Conv_output_0 = self.conv6(x2paddle__stage2_stage2_1_Gather_1_output_0)
        x2paddle__stage2_stage2_1_branch_main_branch_main_2_Relu_output_0 = self.relu4(x2paddle__stage2_stage2_1_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage2_stage2_1_branch_main_branch_main_3_Conv_output_0 = self.conv7(x2paddle__stage2_stage2_1_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage2_stage2_1_branch_main_branch_main_5_Conv_output_0 = self.conv8(x2paddle__stage2_stage2_1_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage2_stage2_1_branch_main_branch_main_7_Relu_output_0 = self.relu5(x2paddle__stage2_stage2_1_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage2_stage2_1_Concat_output_0 = paddle.concat(x=[x2paddle__stage2_stage2_1_Gather_output_0, x2paddle__stage2_stage2_1_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage2_stage2_2_Reshape_output_0 = paddle.reshape(x=x2paddle__stage2_stage2_1_Concat_output_0, shape=[24, 2, 784])
        x2paddle__stage2_stage2_2_Transpose_output_0 = paddle.transpose(x=x2paddle__stage2_stage2_2_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage2_stage2_2_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage2_stage2_2_Transpose_output_0, shape=[2, -1, 24, 28, 28])
        x2paddle__stage2_stage2_2_Gather_output_0 = paddle.gather(x=x2paddle__stage2_stage2_2_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage2_stage2_2_Gather_output_0 = paddle.squeeze(x=x2paddle__stage2_stage2_2_Gather_output_0, axis=[0])
        x2paddle__stage2_stage2_2_Gather_1_output_0 = paddle.gather(x=x2paddle__stage2_stage2_2_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage2_stage2_2_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage2_stage2_2_Gather_1_output_0, axis=[0])
        x2paddle__stage2_stage2_2_branch_main_branch_main_0_Conv_output_0 = self.conv9(x2paddle__stage2_stage2_2_Gather_1_output_0)
        x2paddle__stage2_stage2_2_branch_main_branch_main_2_Relu_output_0 = self.relu6(x2paddle__stage2_stage2_2_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage2_stage2_2_branch_main_branch_main_3_Conv_output_0 = self.conv10(x2paddle__stage2_stage2_2_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage2_stage2_2_branch_main_branch_main_5_Conv_output_0 = self.conv11(x2paddle__stage2_stage2_2_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage2_stage2_2_branch_main_branch_main_7_Relu_output_0 = self.relu7(x2paddle__stage2_stage2_2_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage2_stage2_2_Concat_output_0 = paddle.concat(x=[x2paddle__stage2_stage2_2_Gather_output_0, x2paddle__stage2_stage2_2_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage2_stage2_3_Reshape_output_0 = paddle.reshape(x=x2paddle__stage2_stage2_2_Concat_output_0, shape=[24, 2, 784])
        x2paddle__stage2_stage2_3_Transpose_output_0 = paddle.transpose(x=x2paddle__stage2_stage2_3_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage2_stage2_3_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage2_stage2_3_Transpose_output_0, shape=[2, -1, 24, 28, 28])
        x2paddle__stage2_stage2_3_Gather_output_0 = paddle.gather(x=x2paddle__stage2_stage2_3_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage2_stage2_3_Gather_output_0 = paddle.squeeze(x=x2paddle__stage2_stage2_3_Gather_output_0, axis=[0])
        x2paddle__stage2_stage2_3_Gather_1_output_0 = paddle.gather(x=x2paddle__stage2_stage2_3_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage2_stage2_3_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage2_stage2_3_Gather_1_output_0, axis=[0])
        x2paddle__stage2_stage2_3_branch_main_branch_main_0_Conv_output_0 = self.conv12(x2paddle__stage2_stage2_3_Gather_1_output_0)
        x2paddle__stage2_stage2_3_branch_main_branch_main_2_Relu_output_0 = self.relu8(x2paddle__stage2_stage2_3_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage2_stage2_3_branch_main_branch_main_3_Conv_output_0 = self.conv13(x2paddle__stage2_stage2_3_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage2_stage2_3_branch_main_branch_main_5_Conv_output_0 = self.conv14(x2paddle__stage2_stage2_3_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage2_stage2_3_branch_main_branch_main_7_Relu_output_0 = self.relu9(x2paddle__stage2_stage2_3_branch_main_branch_main_5_Conv_output_0)
        x2paddle_input_136 = paddle.concat(x=[x2paddle__stage2_stage2_3_Gather_output_0, x2paddle__stage2_stage2_3_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage3_stage3_0_branch_proj_branch_proj_0_Conv_output_0 = self.conv15(x2paddle_input_136)
        x2paddle__stage3_stage3_0_branch_main_branch_main_0_Conv_output_0 = self.conv16(x2paddle_input_136)
        x2paddle__stage3_stage3_0_branch_proj_branch_proj_2_Conv_output_0 = self.conv17(x2paddle__stage3_stage3_0_branch_proj_branch_proj_0_Conv_output_0)
        x2paddle__stage3_stage3_0_branch_main_branch_main_2_Relu_output_0 = self.relu10(x2paddle__stage3_stage3_0_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage3_stage3_0_branch_proj_branch_proj_4_Relu_output_0 = self.relu11(x2paddle__stage3_stage3_0_branch_proj_branch_proj_2_Conv_output_0)
        x2paddle__stage3_stage3_0_branch_main_branch_main_3_Conv_output_0 = self.conv18(x2paddle__stage3_stage3_0_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage3_stage3_0_branch_main_branch_main_5_Conv_output_0 = self.conv19(x2paddle__stage3_stage3_0_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage3_stage3_0_branch_main_branch_main_7_Relu_output_0 = self.relu12(x2paddle__stage3_stage3_0_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage3_stage3_0_Concat_output_0 = paddle.concat(x=[x2paddle__stage3_stage3_0_branch_proj_branch_proj_4_Relu_output_0, x2paddle__stage3_stage3_0_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage3_stage3_1_Reshape_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_0_Concat_output_0, shape=[48, 2, 196])
        x2paddle__stage3_stage3_1_Transpose_output_0 = paddle.transpose(x=x2paddle__stage3_stage3_1_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage3_stage3_1_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_1_Transpose_output_0, shape=[2, -1, 48, 14, 14])
        x2paddle__stage3_stage3_1_Gather_output_0 = paddle.gather(x=x2paddle__stage3_stage3_1_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage3_stage3_1_Gather_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_1_Gather_output_0, axis=[0])
        x2paddle__stage3_stage3_1_Gather_1_output_0 = paddle.gather(x=x2paddle__stage3_stage3_1_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage3_stage3_1_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_1_Gather_1_output_0, axis=[0])
        x2paddle__stage3_stage3_1_branch_main_branch_main_0_Conv_output_0 = self.conv20(x2paddle__stage3_stage3_1_Gather_1_output_0)
        x2paddle__stage3_stage3_1_branch_main_branch_main_2_Relu_output_0 = self.relu13(x2paddle__stage3_stage3_1_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage3_stage3_1_branch_main_branch_main_3_Conv_output_0 = self.conv21(x2paddle__stage3_stage3_1_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage3_stage3_1_branch_main_branch_main_5_Conv_output_0 = self.conv22(x2paddle__stage3_stage3_1_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage3_stage3_1_branch_main_branch_main_7_Relu_output_0 = self.relu14(x2paddle__stage3_stage3_1_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage3_stage3_1_Concat_output_0 = paddle.concat(x=[x2paddle__stage3_stage3_1_Gather_output_0, x2paddle__stage3_stage3_1_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage3_stage3_2_Reshape_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_1_Concat_output_0, shape=[48, 2, 196])
        x2paddle__stage3_stage3_2_Transpose_output_0 = paddle.transpose(x=x2paddle__stage3_stage3_2_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage3_stage3_2_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_2_Transpose_output_0, shape=[2, -1, 48, 14, 14])
        x2paddle__stage3_stage3_2_Gather_output_0 = paddle.gather(x=x2paddle__stage3_stage3_2_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage3_stage3_2_Gather_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_2_Gather_output_0, axis=[0])
        x2paddle__stage3_stage3_2_Gather_1_output_0 = paddle.gather(x=x2paddle__stage3_stage3_2_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage3_stage3_2_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_2_Gather_1_output_0, axis=[0])
        x2paddle__stage3_stage3_2_branch_main_branch_main_0_Conv_output_0 = self.conv23(x2paddle__stage3_stage3_2_Gather_1_output_0)
        x2paddle__stage3_stage3_2_branch_main_branch_main_2_Relu_output_0 = self.relu15(x2paddle__stage3_stage3_2_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage3_stage3_2_branch_main_branch_main_3_Conv_output_0 = self.conv24(x2paddle__stage3_stage3_2_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage3_stage3_2_branch_main_branch_main_5_Conv_output_0 = self.conv25(x2paddle__stage3_stage3_2_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage3_stage3_2_branch_main_branch_main_7_Relu_output_0 = self.relu16(x2paddle__stage3_stage3_2_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage3_stage3_2_Concat_output_0 = paddle.concat(x=[x2paddle__stage3_stage3_2_Gather_output_0, x2paddle__stage3_stage3_2_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage3_stage3_3_Reshape_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_2_Concat_output_0, shape=[48, 2, 196])
        x2paddle__stage3_stage3_3_Transpose_output_0 = paddle.transpose(x=x2paddle__stage3_stage3_3_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage3_stage3_3_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_3_Transpose_output_0, shape=[2, -1, 48, 14, 14])
        x2paddle__stage3_stage3_3_Gather_output_0 = paddle.gather(x=x2paddle__stage3_stage3_3_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage3_stage3_3_Gather_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_3_Gather_output_0, axis=[0])
        x2paddle__stage3_stage3_3_Gather_1_output_0 = paddle.gather(x=x2paddle__stage3_stage3_3_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage3_stage3_3_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_3_Gather_1_output_0, axis=[0])
        x2paddle__stage3_stage3_3_branch_main_branch_main_0_Conv_output_0 = self.conv26(x2paddle__stage3_stage3_3_Gather_1_output_0)
        x2paddle__stage3_stage3_3_branch_main_branch_main_2_Relu_output_0 = self.relu17(x2paddle__stage3_stage3_3_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage3_stage3_3_branch_main_branch_main_3_Conv_output_0 = self.conv27(x2paddle__stage3_stage3_3_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage3_stage3_3_branch_main_branch_main_5_Conv_output_0 = self.conv28(x2paddle__stage3_stage3_3_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage3_stage3_3_branch_main_branch_main_7_Relu_output_0 = self.relu18(x2paddle__stage3_stage3_3_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage3_stage3_3_Concat_output_0 = paddle.concat(x=[x2paddle__stage3_stage3_3_Gather_output_0, x2paddle__stage3_stage3_3_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage3_stage3_4_Reshape_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_3_Concat_output_0, shape=[48, 2, 196])
        x2paddle__stage3_stage3_4_Transpose_output_0 = paddle.transpose(x=x2paddle__stage3_stage3_4_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage3_stage3_4_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_4_Transpose_output_0, shape=[2, -1, 48, 14, 14])
        x2paddle__stage3_stage3_4_Gather_output_0 = paddle.gather(x=x2paddle__stage3_stage3_4_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage3_stage3_4_Gather_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_4_Gather_output_0, axis=[0])
        x2paddle__stage3_stage3_4_Gather_1_output_0 = paddle.gather(x=x2paddle__stage3_stage3_4_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage3_stage3_4_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_4_Gather_1_output_0, axis=[0])
        x2paddle__stage3_stage3_4_branch_main_branch_main_0_Conv_output_0 = self.conv29(x2paddle__stage3_stage3_4_Gather_1_output_0)
        x2paddle__stage3_stage3_4_branch_main_branch_main_2_Relu_output_0 = self.relu19(x2paddle__stage3_stage3_4_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage3_stage3_4_branch_main_branch_main_3_Conv_output_0 = self.conv30(x2paddle__stage3_stage3_4_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage3_stage3_4_branch_main_branch_main_5_Conv_output_0 = self.conv31(x2paddle__stage3_stage3_4_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage3_stage3_4_branch_main_branch_main_7_Relu_output_0 = self.relu20(x2paddle__stage3_stage3_4_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage3_stage3_4_Concat_output_0 = paddle.concat(x=[x2paddle__stage3_stage3_4_Gather_output_0, x2paddle__stage3_stage3_4_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage3_stage3_5_Reshape_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_4_Concat_output_0, shape=[48, 2, 196])
        x2paddle__stage3_stage3_5_Transpose_output_0 = paddle.transpose(x=x2paddle__stage3_stage3_5_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage3_stage3_5_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_5_Transpose_output_0, shape=[2, -1, 48, 14, 14])
        x2paddle__stage3_stage3_5_Gather_output_0 = paddle.gather(x=x2paddle__stage3_stage3_5_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage3_stage3_5_Gather_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_5_Gather_output_0, axis=[0])
        x2paddle__stage3_stage3_5_Gather_1_output_0 = paddle.gather(x=x2paddle__stage3_stage3_5_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage3_stage3_5_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_5_Gather_1_output_0, axis=[0])
        x2paddle__stage3_stage3_5_branch_main_branch_main_0_Conv_output_0 = self.conv32(x2paddle__stage3_stage3_5_Gather_1_output_0)
        x2paddle__stage3_stage3_5_branch_main_branch_main_2_Relu_output_0 = self.relu21(x2paddle__stage3_stage3_5_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage3_stage3_5_branch_main_branch_main_3_Conv_output_0 = self.conv33(x2paddle__stage3_stage3_5_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage3_stage3_5_branch_main_branch_main_5_Conv_output_0 = self.conv34(x2paddle__stage3_stage3_5_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage3_stage3_5_branch_main_branch_main_7_Relu_output_0 = self.relu22(x2paddle__stage3_stage3_5_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage3_stage3_5_Concat_output_0 = paddle.concat(x=[x2paddle__stage3_stage3_5_Gather_output_0, x2paddle__stage3_stage3_5_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage3_stage3_6_Reshape_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_5_Concat_output_0, shape=[48, 2, 196])
        x2paddle__stage3_stage3_6_Transpose_output_0 = paddle.transpose(x=x2paddle__stage3_stage3_6_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage3_stage3_6_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_6_Transpose_output_0, shape=[2, -1, 48, 14, 14])
        x2paddle__stage3_stage3_6_Gather_output_0 = paddle.gather(x=x2paddle__stage3_stage3_6_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage3_stage3_6_Gather_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_6_Gather_output_0, axis=[0])
        x2paddle__stage3_stage3_6_Gather_1_output_0 = paddle.gather(x=x2paddle__stage3_stage3_6_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage3_stage3_6_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_6_Gather_1_output_0, axis=[0])
        x2paddle__stage3_stage3_6_branch_main_branch_main_0_Conv_output_0 = self.conv35(x2paddle__stage3_stage3_6_Gather_1_output_0)
        x2paddle__stage3_stage3_6_branch_main_branch_main_2_Relu_output_0 = self.relu23(x2paddle__stage3_stage3_6_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage3_stage3_6_branch_main_branch_main_3_Conv_output_0 = self.conv36(x2paddle__stage3_stage3_6_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage3_stage3_6_branch_main_branch_main_5_Conv_output_0 = self.conv37(x2paddle__stage3_stage3_6_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage3_stage3_6_branch_main_branch_main_7_Relu_output_0 = self.relu24(x2paddle__stage3_stage3_6_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage3_stage3_6_Concat_output_0 = paddle.concat(x=[x2paddle__stage3_stage3_6_Gather_output_0, x2paddle__stage3_stage3_6_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage3_stage3_7_Reshape_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_6_Concat_output_0, shape=[48, 2, 196])
        x2paddle__stage3_stage3_7_Transpose_output_0 = paddle.transpose(x=x2paddle__stage3_stage3_7_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage3_stage3_7_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage3_stage3_7_Transpose_output_0, shape=[2, -1, 48, 14, 14])
        x2paddle__stage3_stage3_7_Gather_output_0 = paddle.gather(x=x2paddle__stage3_stage3_7_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage3_stage3_7_Gather_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_7_Gather_output_0, axis=[0])
        x2paddle__stage3_stage3_7_Gather_1_output_0 = paddle.gather(x=x2paddle__stage3_stage3_7_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage3_stage3_7_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage3_stage3_7_Gather_1_output_0, axis=[0])
        x2paddle__stage3_stage3_7_branch_main_branch_main_0_Conv_output_0 = self.conv38(x2paddle__stage3_stage3_7_Gather_1_output_0)
        x2paddle__stage3_stage3_7_branch_main_branch_main_2_Relu_output_0 = self.relu25(x2paddle__stage3_stage3_7_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage3_stage3_7_branch_main_branch_main_3_Conv_output_0 = self.conv39(x2paddle__stage3_stage3_7_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage3_stage3_7_branch_main_branch_main_5_Conv_output_0 = self.conv40(x2paddle__stage3_stage3_7_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage3_stage3_7_branch_main_branch_main_7_Relu_output_0 = self.relu26(x2paddle__stage3_stage3_7_branch_main_branch_main_5_Conv_output_0)
        x2paddle_input_376 = paddle.concat(x=[x2paddle__stage3_stage3_7_Gather_output_0, x2paddle__stage3_stage3_7_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage4_stage4_0_branch_proj_branch_proj_0_Conv_output_0 = self.conv41(x2paddle_input_376)
        x2paddle__stage4_stage4_0_branch_main_branch_main_0_Conv_output_0 = self.conv42(x2paddle_input_376)
        x2paddle__stage4_stage4_0_branch_proj_branch_proj_2_Conv_output_0 = self.conv43(x2paddle__stage4_stage4_0_branch_proj_branch_proj_0_Conv_output_0)
        x2paddle__stage4_stage4_0_branch_main_branch_main_2_Relu_output_0 = self.relu27(x2paddle__stage4_stage4_0_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage4_stage4_0_branch_proj_branch_proj_4_Relu_output_0 = self.relu28(x2paddle__stage4_stage4_0_branch_proj_branch_proj_2_Conv_output_0)
        x2paddle__stage4_stage4_0_branch_main_branch_main_3_Conv_output_0 = self.conv44(x2paddle__stage4_stage4_0_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage4_stage4_0_branch_main_branch_main_5_Conv_output_0 = self.conv45(x2paddle__stage4_stage4_0_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage4_stage4_0_branch_main_branch_main_7_Relu_output_0 = self.relu29(x2paddle__stage4_stage4_0_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage4_stage4_0_Concat_output_0 = paddle.concat(x=[x2paddle__stage4_stage4_0_branch_proj_branch_proj_4_Relu_output_0, x2paddle__stage4_stage4_0_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage4_stage4_1_Reshape_output_0 = paddle.reshape(x=x2paddle__stage4_stage4_0_Concat_output_0, shape=[96, 2, 49])
        x2paddle__stage4_stage4_1_Transpose_output_0 = paddle.transpose(x=x2paddle__stage4_stage4_1_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage4_stage4_1_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage4_stage4_1_Transpose_output_0, shape=[2, -1, 96, 7, 7])
        x2paddle__stage4_stage4_1_Gather_output_0 = paddle.gather(x=x2paddle__stage4_stage4_1_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage4_stage4_1_Gather_output_0 = paddle.squeeze(x=x2paddle__stage4_stage4_1_Gather_output_0, axis=[0])
        x2paddle__stage4_stage4_1_Gather_1_output_0 = paddle.gather(x=x2paddle__stage4_stage4_1_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage4_stage4_1_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage4_stage4_1_Gather_1_output_0, axis=[0])
        x2paddle__stage4_stage4_1_branch_main_branch_main_0_Conv_output_0 = self.conv46(x2paddle__stage4_stage4_1_Gather_1_output_0)
        x2paddle__stage4_stage4_1_branch_main_branch_main_2_Relu_output_0 = self.relu30(x2paddle__stage4_stage4_1_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage4_stage4_1_branch_main_branch_main_3_Conv_output_0 = self.conv47(x2paddle__stage4_stage4_1_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage4_stage4_1_branch_main_branch_main_5_Conv_output_0 = self.conv48(x2paddle__stage4_stage4_1_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage4_stage4_1_branch_main_branch_main_7_Relu_output_0 = self.relu31(x2paddle__stage4_stage4_1_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage4_stage4_1_Concat_output_0 = paddle.concat(x=[x2paddle__stage4_stage4_1_Gather_output_0, x2paddle__stage4_stage4_1_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage4_stage4_2_Reshape_output_0 = paddle.reshape(x=x2paddle__stage4_stage4_1_Concat_output_0, shape=[96, 2, 49])
        x2paddle__stage4_stage4_2_Transpose_output_0 = paddle.transpose(x=x2paddle__stage4_stage4_2_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage4_stage4_2_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage4_stage4_2_Transpose_output_0, shape=[2, -1, 96, 7, 7])
        x2paddle__stage4_stage4_2_Gather_output_0 = paddle.gather(x=x2paddle__stage4_stage4_2_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage4_stage4_2_Gather_output_0 = paddle.squeeze(x=x2paddle__stage4_stage4_2_Gather_output_0, axis=[0])
        x2paddle__stage4_stage4_2_Gather_1_output_0 = paddle.gather(x=x2paddle__stage4_stage4_2_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage4_stage4_2_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage4_stage4_2_Gather_1_output_0, axis=[0])
        x2paddle__stage4_stage4_2_branch_main_branch_main_0_Conv_output_0 = self.conv49(x2paddle__stage4_stage4_2_Gather_1_output_0)
        x2paddle__stage4_stage4_2_branch_main_branch_main_2_Relu_output_0 = self.relu32(x2paddle__stage4_stage4_2_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage4_stage4_2_branch_main_branch_main_3_Conv_output_0 = self.conv50(x2paddle__stage4_stage4_2_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage4_stage4_2_branch_main_branch_main_5_Conv_output_0 = self.conv51(x2paddle__stage4_stage4_2_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage4_stage4_2_branch_main_branch_main_7_Relu_output_0 = self.relu33(x2paddle__stage4_stage4_2_branch_main_branch_main_5_Conv_output_0)
        x2paddle__stage4_stage4_2_Concat_output_0 = paddle.concat(x=[x2paddle__stage4_stage4_2_Gather_output_0, x2paddle__stage4_stage4_2_branch_main_branch_main_7_Relu_output_0], axis=1)
        x2paddle__stage4_stage4_3_Reshape_output_0 = paddle.reshape(x=x2paddle__stage4_stage4_2_Concat_output_0, shape=[96, 2, 49])
        x2paddle__stage4_stage4_3_Transpose_output_0 = paddle.transpose(x=x2paddle__stage4_stage4_3_Reshape_output_0, perm=[1, 0, 2])
        x2paddle__stage4_stage4_3_Reshape_1_output_0 = paddle.reshape(x=x2paddle__stage4_stage4_3_Transpose_output_0, shape=[2, -1, 96, 7, 7])
        x2paddle__stage4_stage4_3_Gather_output_0 = paddle.gather(x=x2paddle__stage4_stage4_3_Reshape_1_output_0, index=x2paddle__stage2_stage2_1_Constant_2_output_0, axis=0)
        x2paddle__stage4_stage4_3_Gather_output_0 = paddle.squeeze(x=x2paddle__stage4_stage4_3_Gather_output_0, axis=[0])
        x2paddle__stage4_stage4_3_Gather_1_output_0 = paddle.gather(x=x2paddle__stage4_stage4_3_Reshape_1_output_0, index=x2paddle__first_conv_first_conv_0_Constant_output_0, axis=0)
        x2paddle__stage4_stage4_3_Gather_1_output_0 = paddle.squeeze(x=x2paddle__stage4_stage4_3_Gather_1_output_0, axis=[0])
        x2paddle__stage4_stage4_3_branch_main_branch_main_0_Conv_output_0 = self.conv52(x2paddle__stage4_stage4_3_Gather_1_output_0)
        x2paddle__stage4_stage4_3_branch_main_branch_main_2_Relu_output_0 = self.relu34(x2paddle__stage4_stage4_3_branch_main_branch_main_0_Conv_output_0)
        x2paddle__stage4_stage4_3_branch_main_branch_main_3_Conv_output_0 = self.conv53(x2paddle__stage4_stage4_3_branch_main_branch_main_2_Relu_output_0)
        x2paddle__stage4_stage4_3_branch_main_branch_main_5_Conv_output_0 = self.conv54(x2paddle__stage4_stage4_3_branch_main_branch_main_3_Conv_output_0)
        x2paddle__stage4_stage4_3_branch_main_branch_main_7_Relu_output_0 = self.relu35(x2paddle__stage4_stage4_3_branch_main_branch_main_5_Conv_output_0)
        x2paddle_586 = paddle.concat(x=[x2paddle__stage4_stage4_3_Gather_output_0, x2paddle__stage4_stage4_3_branch_main_branch_main_7_Relu_output_0], axis=1)
        return x2paddle_input_136, x2paddle_input_376, x2paddle_586

def main(x2paddle_input_1):
    # There are 1 inputs.
    # x2paddle_input_1: shape-[1, 3, 224, 224], type-float32.
    paddle.disable_static()
    params = paddle.load(r'/home/galaxy/MyWorks/X2Paddle/pd_model/model.pdparams')
    model = ONNXModel()
    model.set_dict(params, use_structured_name=True)
    model.eval()
    out = model(x2paddle_input_1)
    return out
